t=-10:0.01:10;
T=4;
fm=1/T;
x=cos(2*pi*fm*t);
subplot(2,2,1);
plot(t,x);
xlabel('time');
ylabel('amplitude');
title('continuous time signal');
grid;
fs1=1.7*fm;
fs2=2*fm;
fs3=5*fm;
x1=cos(2*pi*fm/fs1*t);
subplot(2,2,2);
stem(t,x1);
xlabel('time');
ylabel('x(n)');
title('Discrete time signal');
hold on;
subplot(2,2,2);
plot(t,x1);
grid;
x2=cos(2*pi*fm/fs2*t);
subplot(2,2,3);
stem(t,x2);
xlabel('time');
ylabel('x(n)');
title('Discrete time signal with fs=2fm');
hold on ;
subplot(2,2,3);
stem(t,x2);
grid;
x3=cos(2*pi*fm/fs3*t);
subplot(2,2,4);
stem(t,x3);
xlabel('time');
ylabel('x(n)');
title('Discrete time signal with fs>2fm');
hold on ;
subplot(2,2,4);
stem(t,x3);
grid;

